import type { Project } from "./types";

/**
 * One array for both WORKS and LAB — section decides placement, not
 * medium. Ported from the locked mockup's sample catalog: concrete,
 * non-lorem placeholder content, swap-ready for the real project list.
 */
export const projects: Project[] = [
  // ---------- WORKS ----------
  {
    slug: "nocturne-studio",
    index: "W01",
    title: "Nocturne Studio",
    summary: "Website + art direction for a mastering studio",
    section: "works",
    category: "websites",
    meta: "NEXT.JS · 2026",
    year: 2026,
    status: "LIVE",
    live: true,
    caseStudy: {
      body: "A mastering studio with no site and a booking form living in someone's DMs. Built the identity out from their console, then a site that lets you hear the room before you book it — before/after players on every service page.",
    },
  },
  {
    slug: "patchbay",
    index: "W02",
    title: "Patchbay",
    summary: "Signal-routing tool you can drag, hear, and export",
    section: "works",
    category: "experiences",
    meta: "TYPESCRIPT · 2026",
    year: 2026,
    status: "LIVE",
    live: true,
  },
  {
    slug: "side-b-records",
    index: "W03",
    title: "Side B Records",
    summary: "Identity, sleeve system, and release microsites",
    section: "works",
    category: "direction",
    meta: "BRAND · 2025",
    year: 2025,
    status: "ARCHIVE",
    live: false,
  },
  {
    slug: "ferria-coffee",
    index: "W04",
    title: "Ferria Coffee",
    summary: "Storefront rebuild — 2.1s to 0.6s first paint",
    section: "works",
    category: "websites",
    meta: "SHOPIFY · 2025",
    year: 2025,
    status: "LIVE",
    live: true,
  },
  {
    slug: "rooms-we-left",
    index: "W05",
    title: "Rooms We Left",
    summary: "Photo series and print run, 18 interiors",
    section: "works",
    category: "visual",
    meta: "35MM · 2025",
    year: 2025,
    status: "ARCHIVE",
    live: false,
  },
  {
    slug: "halo-festival",
    index: "W06",
    title: "Halo Festival",
    summary: "Stage visuals and a live web companion",
    section: "works",
    category: "experiences",
    meta: "WEBGL · 2024",
    year: 2024,
    status: "ARCHIVE",
    live: false,
  },

  // ---------- LAB ----------
  {
    slug: "library-organizer",
    index: "LAB 01",
    title: "Library Organizer",
    summary: "Reads 40k audio files, infers genre from the spectrum, rewrites the tree.",
    section: "lab",
    category: "code",
    meta: "v0.7.2",
    year: 2026,
    status: "RUNNING",
    live: true,
    level: 0.86,
  },
  {
    slug: "after-hours",
    index: "LAB 02",
    title: "After Hours",
    summary: "Sixty minutes, one take, recorded at 03:12AM. No edits, no rescue.",
    section: "lab",
    category: "dj",
    meta: "60:21",
    year: 2026,
    status: "MIXED",
    live: false,
    level: 0.94,
  },
  {
    slug: "cassette-os",
    index: "LAB 03",
    title: "Cassette OS",
    summary: "Tape emulation as a VST3. Wow, flutter and bias modeled per deck.",
    section: "lab",
    category: "audio",
    meta: "v1.1.4",
    year: 2025,
    status: "SHIPPED",
    live: false,
    level: 0.71,
  },
  {
    slug: "room-tone",
    index: "LAB 04",
    title: "Room Tone",
    summary: "Eighteen rooms shot on 35mm and recorded binaurally in the same hour.",
    section: "lab",
    category: "photo",
    meta: "18 SITES",
    year: 2025,
    status: "OPEN",
    live: true,
    level: 0.44,
  },
  {
    slug: "scope-type",
    index: "LAB 05",
    title: "Scope Type",
    summary: "A typeface that redraws itself from an audio signal. Barely legible. Worth it.",
    section: "lab",
    category: "proto",
    meta: "v0.2.0",
    year: 2026,
    status: "WEIRD",
    live: false,
    level: 0.31,
  },
  {
    slug: "this-site",
    index: "LAB 06",
    title: "This Site",
    summary: "Hand-built, no template. The identity is the interface.",
    section: "lab",
    category: "code",
    meta: "v0.1.0",
    year: 2026,
    status: "BUILDING",
    live: true,
    level: 0.22,
  },
];

export function getProjectBySlug(slug: string): Project | undefined {
  return projects.find((project) => project.slug === slug);
}
